// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIUrWq72_j13wfCcqo5dSdUbMe2zJxWTE',
    appId: '1:1018833049347:web:e3452130ac9bf119243b36',
    messagingSenderId: '1018833049347',
    projectId: 'pupad-2a339',
    authDomain: 'pupad-2a339.firebaseapp.com',
    storageBucket: 'pupad-2a339.appspot.com',
    measurementId: 'G-GK6LZF9702',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgLfU-wWyfGdTdNiXj9Z7mUwVPEWB4ZEw',
    appId: '1:1018833049347:android:0f19883420b1b149243b36',
    messagingSenderId: '1018833049347',
    projectId: 'pupad-2a339',
    storageBucket: 'pupad-2a339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2_pv_UMc9i6h0vwTFFcZUtyohwU3hGU',
    appId: '1:1018833049347:ios:ed309bd9ee3dc1f6243b36',
    messagingSenderId: '1018833049347',
    projectId: 'pupad-2a339',
    storageBucket: 'pupad-2a339.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb2_pv_UMc9i6h0vwTFFcZUtyohwU3hGU',
    appId: '1:1018833049347:ios:ed309bd9ee3dc1f6243b36',
    messagingSenderId: '1018833049347',
    projectId: 'pupad-2a339',
    storageBucket: 'pupad-2a339.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );
}
